<?php


// Translation of file /modules/footer/views.php

$_COS_LANG_MODULE['Footer license'] = '2014. Unauthorized use and/or duplication of this material without express and written permission from this author and/or owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to this site, with appropriate and specific direction to the original content.';
