<?php

$_COS_LANG_MODULE['Footer license'] = '2014. Die nicht autorisierte Verwendung und / oder Vervielfältigung dieses Materials ohne ausdrückliche und schriftliche Genehmigung von diesem Autor und / oder Eigentümer ist strikt verboten. Auszüge und Links können verwendet werden, vorausgesetzt, dass die vollständige und klare Kredit ist an dieser Seite, mit angemessenen und bestimmte Richtung zu dem ursprünglichen Inhalt gegeben.';
